version: "3.8"

services:

  # ========================================
  # FRONTEND (NGINX)
  # ========================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - devops-net

  # ========================================
  # BACKEND (NODE + SQLITE)
  # ========================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-api
    ports:
      - "4000:4000"
    volumes:
      - backend-db:/app     # BANCO FICA DENTRO DO CONTAINER (CORRETO)
    networks:
      - devops-net

  # ========================================
  # ZABBIX SERVER
  # ========================================
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    depends_on:
      - zabbix-db
    ports:
      - "10051:10051"
    networks:
      - devops-net

  # ========================================
  # ZABBIX DATABASE (POSTGRES)
  # ========================================
  zabbix-db:
    image: postgres:15
    container_name: zabbix-db
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - zabbix-db:/var/lib/postgresql/data
    networks:
      - devops-net

  # ========================================
  # ZABBIX WEB (interface web)
  # ========================================
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - "8081:8080"
    depends_on:
      - zabbix-server
    networks:
      - devops-net

  # ========================================
  # ZABBIX AGENT
  # ========================================
  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
    networks:
      - devops-net

  # ========================================
  # GRAFANA
  # ========================================
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - devops-net


# ========================================
# REDES E VOLUMES
# ========================================
networks:
  devops-net:

volumes:
  backend-db:
  zabbix-db:
  grafana-data:
